default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy new app to Google Play"
  lane :deploy do
    gradle(task: "clean")
    gradle(
      task: 'assemble',
      flavor: 'Dev',
      build_type: 'Release'
    )
    upload_to_play_store
  end
end
