default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy beta app to Google Play"
  lane :beta do |options|
    gradle(task: "clean")
    gradle(
      task: 'assemble',
      flavor: 'Beta',
      build_type: 'Beta'
    )
    if options[:upload_store]
      upload_to_play_store
    end
  end
  desc "Deploy prod app to Google Play"
  lane :prod do |options|
    gradle(task: "clean")
    gradle(
      task: 'assemble',
      flavor: 'Prod',
      build_type: 'Prod'
    )
    if options[:upload_store]
      upload_to_play_store
    end
  end
end
