default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy beta app to Google Play"
  lane :beta do
    gradle(task: "clean")
    gradle(
      task: 'assemble',
      build_type: 'Beta'
    )
    upload_to_play_store
  end
  desc "Deploy prod app to Google Play"
  lane :prod do
    gradle(task: "clean")
    gradle(
      task: 'assemble',
      build_type: 'Prod'
    )
    upload_to_play_store
  end
end
