name: Build app
on:
  push:
    branches: [beta, master]
  pull_request:
    branches: [beta, master]

jobs:
  build:
    name: Build common and testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        id: node-modules
        env:
          cache-name: node-modules
        with:
          path: CICD/node_modules
          key: ${{ runner.os }}-cache-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ env.cache-name }}-
            ${{ runner.os }}-cache-
            ${{ runner.os }}-

      - name: Install Node Dependencies
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: |
          rm -rf node_modules
          rm -rf ~/.rncache
          cd CICD && yarn cache clean && yarn install

      - name: Run unit test
        run: |
          cd CICD && yarn test --coverage

  ios:
    name: Build iOS
    runs-on: macos-10.15
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "14.2.0"

      - name: Install react-native-cli
        run: |
          cd CICD && yarn add react-native-cli

      - name: Install fastlane
        run: |
          brew update
          brew install ruby
          sudo gem install fastlane -NV

      - name: Bundler install
        run: |
          cd CICD/ios
          sudo gem install json
          bundle update --all
          bundle install --path vendor/bundle

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        id: node-modules-ios
        env:
          cache-name: node-modules-ios
        with:
          path: CICD/node_modules
          key: ${{ runner.os }}-cache-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ env.cache-name }}-
            ${{ runner.os }}-cache-
            ${{ runner.os }}-

      - name: Install Node Dependencies
        if: steps.node-modules-ios.outputs.cache-hit != 'true'
        run: |
          rm -rf node_modules
          rm -rf ~/.rncache
          cd CICD && yarn cache clean && yarn install

      # Notes: Create main.jsbundle https://github.com/facebook/react-native/issues/18472
      - name: Create a main.jsbundle
        run: |
          cd CICD
          node ./node_modules/react-native-cli/index.js bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios'

      # NOTES: Only run tests
      - name: Build and upload ipa to S3 internal
        run: |
          python -c "import hashlib;m=hashlib.md5();print(m.hexdigest())"
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          cd CICD/ios
          bundle exec fastlane tests

  android:
    name: Build Android
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Start
        run: echo "Starting build"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "14.2.0"

      - name: Install react-native-cli
        run: cd CICD && yarn add react-native-cli

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        id: node-modules-android
        env:
          cache-name: node-modules
        with:
          path: CICD/node_modules
          key: ${{ runner.os }}-cache-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ env.cache-name }}-
            ${{ runner.os }}-cache-
            ${{ runner.os }}-

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        id: node-modules
        env:
          cache-name: node-modules
        with:
          path: CICD/node_modules
          key: ${{ runner.os }}-cache-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ env.cache-name }}-
            ${{ runner.os }}-cache-
            ${{ runner.os }}-

      - name: Install Node Dependencies
        if: steps.node-modules-android.outputs.cache-hit != 'true'
        run: |
          rm -rf node_modules
          rm -rf ~/.rncache
          cd CICD && yarn cache clean && yarn install

      - name: Install awscli
        run: sudo pip install awscli

      - name: Install gem & fastlane
        run: |
          cd CICD/android
          sudo gem install bundler
          sudo bundle update --all
          sudo gem install json
          sudo bundle install --path vendor/bundle

        # Ref: https://github.com/actions/virtual-environments/pull/539
      - name: Install sdkmanager
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Decode the keystore bate
        if: github.ref == 'refs/heads/beta'
        run: |
          echo "Beta"
          cd CICD/android/app
          echo ${{ secrets.ENCODED_KEYSTORE_BETA }} | sed 's/ /\n/g' | base64 --decode >> beta.keystore

      - name: Decode the keystore prod
        if: github.ref == 'refs/heads/master'
        run: |
          cd CICD/android/app
          echo ${{ secrets.ENCODED_KEYSTORE_PROD }} | sed 's/ /\n/g' | base64 --decode >> release-product.keystore

      - name: Decode google service beta
        if: github.ref == 'refs/heads/beta'
        run: |
          cd CICD/android
          echo ${{ secrets.ENCODED_GOOGLE_SERVICES_BETA }} | sed 's/ /\n/g' | base64 --decode >> google-services.json

      - name: Decode google service prod
        if: github.ref == 'refs/heads/master'
        run: |
          cd CICD/android
          echo ${{ secrets.ENCODED_GOOGLE_SERVICES_PROD }} | sed 's/ /\n/g' | base64 --decode >> google-services.json

      - name: Build APK and Upload to S3/Google play Beta version
        if: github.ref == 'refs/heads/beta'
        run: |
          cd CICD/android
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          echo "APPLICATION_ID=com.cicd.nhanhuynh.app" &>> gradle.properties
          fastlane beta upload_store:true
          aws s3 cp $(pwd)/app/build/outputs/apk/beta/app-beta.apk "s3://${{ secrets.AWS_S3_BUCKET_NAME }}/beta/$(date +'%y-%m-%d-%H-%M')/cicd-beta.apk"

      - name: Build APK and Upload to S3/Google play Prod version
        if: github.ref == 'refs/heads/master'
        run: |
          cd CICD/android
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          echo "APPLICATION_ID=com.cicd.app.pro" &>> gradle.properties
          fastlane beta upload_store:true
          aws s3 cp $(pwd)/app/build/outputs/apk/prod/app-prod.apk "s3://${{ secrets.AWS_S3_BUCKET_NAME }}/prod/$(date +'%y-%m-%d-%H-%M')/cicd-prod.apk"
